=== okta/workflows-templates/scripts/workflow-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://oinmanager.okta.com/v1/bootstrap/integration.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "required": [
        "name",
        "title",
        "description"
    ],
    "additionalProperties": true,
    "properties": {
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "The name schema",
            "pattern": "^[a-z0-9_]{2,50}$",
            "maxLength": 50,
            "minLength": 2,
            "description": "An explanation about the purpose of this instance."
        },
        "title": {
            "$id": "#/properties/title",
            "type": "string",
            "title": "The title schema",
            "description": "An explanation about the purpose of this instance."
        },
        "description": {
            "$id": "#/properties/description",
            "type": "string",
            "title": "The description schema",
            "description": "An explanation about the purpose of this instance."
        },
        "connectors": {
            "$id": "#/properties/connectors",
            "type": "array",
            "title": "The components schema",
            "additionalItems": true,
            "items": {
                    "type": "string",
                    "title": "The first anyOf schema",
                    "description": "An explanation about the purpose of this instance."
                }
            },
        "links": {
            "$id": "#/properties/links",
            "type": "array",
            "title": "The links schema",
            "description": "An explanation about the purpose of this instance.",
            "additionalItems": true,
            "items": {
                "type": "object",
                "required": [
                    "title",
                    "destination"
                ],
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "Link title to be displayed"
                    },
                    "destination": {
                        "type": "string",
                        "format": "uri",
                        "description": "The link destination URI"
                    }
                }
            }
        },
        "features": {
            "$id": "#/properties/features",
            "type": "array",
            "title": "The features schema",
            "description": "An explanation about the purpose of this instance.",
            "additionalItems": true,
            "items": {
                "type": "string",
                "enum": [
                    "SWA",
                    "SAML",
                    "OIDC",
                    "WSFED",
                    "CREATE",
                    "UPDATE",
                    "DEACTIVATE",
                    "SYNC_PASSWORD",
                    "GROUP_LINKING",
                    "SCHEMA_DISCOVERY",
                    "GROUP_PUSH",
                    "ATTRIBUTE_MASTERING",
                    "ATTRIBUTE_WRITEBACK"]
            }
        },
        "logo": {
            "$id": "#/properties/logo",
            "type": "string",
            "format": "uri",
            "title": "The logo uri",
            "description": "The integration logo URI."
        }
    }
}

=== okta/workflows-templates/workflows/onfido_handle_webhook/workflow.json
{
  "name": "onfido_handle_webhook",
  "title": "Onfido Handle Webhook",
  "description": "Provides an API endpoint for Onfido's webhook functionality to send events to. Allows for processing of events including report and check details.",
  "connectors": [
    "okta",
    "http"
  ],
  "links": [
    {
      "title": "Setup Documentation",
      "destination": "https://github.com/jhickmanit/onfido-handle-webhook/blob/master/readme.md"
    }
  ]
}

=== okta/workflows-templates/workflows/GoogleDrive_File_Transfer/workflows.json
{
  "name": "googledrive_reassign_files",
  "title": "Reassign Files while Deprovisioning with Google Drive",
  "description": "In many organizations that use Google Drive, there is a requirement to transfer a user's GDrive contents to another user. Maybe you have users that need to be deactivated - you can transfer the files from the user's GDrive to the Manager and delete the user.",
  "connectors": [
    "googledrive"
  ],
  "links": [
    {
      "title": "Video",
      "destination": "https://www.youtube.com/watch?v=iMuCUhoB0v4"
    },
    {
      "title": "Documentation",
      "destination": "https://github.com/okta/workflows-templates/blob/master/workflows/googledrive_reassign_files/readme.md"
    }
  ]
}

=== okta/workflows-templates/workflows/suspend_inactive_users/workflow.json
{
   "name": "suspend_inactive_users",
   "title": "Suspend Inactive Users",
   "description": "In many organizations, access tends to proliferate for far longer than certain users require it. Maybe you’re working with a contractor who needs access to a single app, or offboarding policies break down for an ex-employee. All of a sudden, you realize that the user hasn’t logged in for months, and as part of a strong security posture, would like to suspend them until you’re notified that they do actually need access. This flow reads all active users in your environment, and if they haven’t logged in within the past 6 months (180 days), suspends them.",
   "connectors": [
      "okta"
   ],
   "links": [
      {
         "title": "Video Walk-through",
         "destination": "https://www.youtube.com/watch?v=AsmGjBjwCps"
      },
      {
         "title": "Setup Documentation",
         "destination": "https://github.com/workflows-templates/workflows/suspend_inactive_users/readme.md"
      }
   ]
}

=== okta/workflows-templates/workflows/manage_okta_group_membership_based_on_profile_attributes/workflows.json
{
  "name": "manage_okta_group_membership_based_on_profile_attributes",
  "title": "Manage Okta Group Membership Based on Profile Attributes",
  "description": "In many organizations a set of Okta group memberships are determined based on Job Codes or more generally, by user profile attributes to implement Role-based access control (RBAC). This template illustrates group assignment based on user profile attributes.",
  "connectors": [
    "okta"
  ],
  "links": [
    {
      "title": "Video",
      "destination": "https://www.youtube.com/watch?v=n6R_d7Iv7nQ"
    },
    {
      "title": "Sample Data",
      "destination": "https://github.com/okta/workflows-templates/blob/master/workflows/manage_okta_group_membership_based_on_profile_attributes/groupRules.csv"
    }, 
    {
      "title": "Documentation",
      "destination": "https://github.com/okta/workflows-templates/blob/master/workflows/manage_okta_group_membership_based_on_profile_attributes/readme.md"

    }
  ]
}

=== okta/workflows-templates/workflows/Initiate-Flow-With-API-Endpoint/workflow.json
{
  "name": "initiate_flow_with_api_endpoint",
  "title": "Initiate Flow with API Endpoint",
  "description": "The Okta Workflow feature is a powerful tool to implement custom business logic. A popular integration is instead of creating an object directly into Okta (i.e. user, application or group ) with the Okta REST APIs, is to send the object request along with itâ€™s JSON payload to Workflows. Then custom business logic such as checking existing objects in Okta or reaching out to a 3rd party to verify data can be accomplished. Based on the results of the dynamic logic, decisions can be made by Workflows providing distinct processing options.",
  "connectors": [
    "okta"
  ],
  "links": [
    {
      "title": "Video Walk-through",
      "destination": "https://www.youtube.com/watch?v=-4M-nEcjA9E"
    },
    {
      "title": "Setup Documentation",
      "destination": "https://github.com/okta/workflows-templates/workflows/Initiate-Flow-With-API-Endpoint/blob/master/README.md"
    }
  ]
}

=== okta/workflows-templates/workflows/import-users-from-google-sheets/workflow.json
{
   "name": "import-users-from-google-sheets",
   "title": "Import Users from Google Sheets",
   "description": "Often, there are disconnected user populations like contractors, or certain offices that need to be imported into Okta. A CSV or Flat File is the easiest way to create those users in Okta. This flow walks you through how to bring in users from Google Sheets and how to use For Each loops. This flow reads all users in a specified Google sheet and, each week on Monday at 6 am, tries to create them in Okta.",
   "connectors": [
      "okta", "google sheets", "gmail"
   ],
   "links": [
      {
         "title": "Video Walk-through",
         "destination": "https://www.youtube.com/watch?v=JYOKbG9o9PA"
      },
      {
         "title": "Setup Documentation",
         "destination": "https://github.com/ryanbradley-okta/import-users-from-google-sheets/blob/master/readme.md"
      }
   ]
}

=== okta/workflows-templates/workflows/salesforce_create_user/workflow.json
{
   "name": "salesforce_create_user",
   "title": "Create Users in Salesfoce",
   "description": "This flow covers a basic onboarding use case with users into Salesforce, including creating the user with the correct Role and Feature License.",
   "connectors": [
      "salesforce"
   ],
   "links": [
      {
         "title": "Video",
         "destination": "https://www.loom.com/share/2fc6dcd7318840968d6711ae68f43ec5"
      },
      {
         "title": "Documentation",
         "destination": "https://help.okta.com/en/prod/Content/Topics/Workflows/workflows-main.htm"
      }
   ]
}
